// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iaotzhimftnjosambovq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlhb3R6aGltZnRuam9zYW1ib3ZxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI1ODk5MzEsImV4cCI6MjA2ODE2NTkzMX0.PH5dlxMQ0Ur6xaNEXC9NTk68u9pCfGagjx0e59WRa4s";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});